### PR TITLE
Add command to fetch a specific language.

### PR DESCRIPTION
**Pull request by tejasbubane**
The command `exercism-fetch` currently fetches all languages.
Adding a new command `exercism-fetch-language` to prompt for a language and fetch only the next exercise for that language. Like `exercism fetch $LANGUAGE` on CLI.

### CODE REVIEW

**Comment by verdammelt** [comment]
Why not have `exercism-fetch` take a default argument, or perhaps check for prefix argument, and when it gets that it prompts for language?

(I suggest this _assuming_ it is "easy" - but I don't actually know).

**Comment by tejasbubane** [comment]
I don't know how prefix arguments are implemented. I will have to look that up. But I thought having 2 separate commands was a cleaner. Maybe we can rename `exercism-fetch` to `exercism-fetch-all` so that the two are distinguishable.

**Comment by canweriotnow** [comment]
I'm good with this for now.. if you read the comments, most everything's going to change once the new API is in place and we can ditch wrapping the CLI, so lots of refactoring can happen down the road :)

**Comment by tejasbubane** [comment]
Yes @canweriotnow, it would be great if this becomes independent of the CLI. :+1:

**Pull request merged**
